name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [1.8]
        python: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK ${{ matrix.jdk }}
        uses: olafurpg/setup-scala@v11
        with:
          java-version: ${{ matrix.jdk }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python: ${{ matrix.python }}
      - name: Unit tests
        run: sbt +test
        shell: bash
      - name: Integration tests again latest ScalaPy stable
        run: .github/scripts/integration_test.sh python3 0.5.0
        shell: bash
